const CREATE_TABLE_SCRIPT = `
  CREATE TABLE events (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fio varchar(100),
    department varchar(100),
    theme varchar(100),
    content varchar(100),
    file varchar(100),
    date varchar(10),
    time varchar(10)
  );
`;

const INSERT_DATA_SCRIPT = `
  INSERT INTO events(
    fio, department, theme, content, file, date, time
  ) VALUES (
    $1, $2, $3, $4, $5, $6, $7
  ) RETURNING *
`;

module.exports = {
  CREATE_TABLE_SCRIPT,
  INSERT_DATA_SCRIPT
};
